name: CI-pipeline-deploy-to-aorta-website
env:  
      EB_PACKAGE_S3_BUCKET_NAME : "aleksei-new-site"
      EB_APPLICATION_NAME       : "new site"
      EB_ENVIRONMENT_NAME       : "new-site-env"
      DEPLOY_PACKAGE_NAME       : "site_${{ github.sha }}.zip"
      AWS_REGION_NAME           : "us-west-2"
  
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: create zip
        run : zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
        
      - name: cred to aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key : ${{ secrets.AWS_SECRET_KEY }}
            aws-region            : ${{ env.AWS_REGION_NAME }}
            
      - name: copy to s3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
        
      - run: echo "DONE!"
